### ISSUE TITLE
select_related antipattern

### ISSUE THREAD

**Issue by ChasNelson1990** [road86/bahis-serve#7]
### Bug Description

As documented in #6, some Django ORM commands have an antipattern that leads to 1000s of SQL requests being created and massively slowing down the system. We need to go through the code and identify any additional places where this occurs and fix.

### To Reproduce

See #6

**Comment by ChasNelson1990** [comment]
@sharful09 - did you find any other examples of this antipattern?
If not, shall we close this with v2.2.x?

**Comment by shaarful** [comment]
Till now I did not see any SQL antipattern. We need to explore more, module by module. We will do it on the next release.
